version: 2
updates:
- package-ecosystem: npm
  directory: "/template"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.4
    - 24.1.5
    - 24.1.8
    - 24.2.0
    - 24.2.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: ts-loader
    versions:
    - 9.1.0
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: scriptlint
    versions:
    - 2.1.2
    - 2.1.3
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: pug-code-gen
    versions:
    - 2.0.3
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.2
    - 32.1.0
    - 32.2.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.4
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
- package-ecosystem: docker
  directory: "/template/docker/vue"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.10.0.pre.alpine
    - 15.11.0.pre.alpine
    - 15.12.0.pre.alpine
    - 15.13.0.pre.alpine
    - 15.14.0.pre.alpine
    - 15.7.0.pre.alpine
    - 15.8.0.pre.alpine
    - 15.9.0.pre.alpine
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
